### ISSUE TITLE
Images are not aligned with Specific height & should be Reponsive

### ISSUE THREAD

**Issue by SikandarJODD** [gdgchennai/devfest2022-web#114]
![image](https://github.com/gdgchennai/devfest2022-web/assets/93428946/4e278f8d-4208-40fe-a4cf-313716e8d0fb)
### Images should be aligned : minimum height & margin-x 10px in Mobile devices 

![image](https://github.com/gdgchennai/devfest2022-web/assets/93428946/eff3eec3-6d98-4039-baa5-13d68db69937)
### Font size should be text-lg ...
can i work on this ?

**Comment by iamimmanuelraj** [comment]
@SikandarJODD Yes. Feel free to work on it. Add the pull request to this issue. ill have it open
