### ISSUE TITLE
Add embedded CFP page

### ISSUE THREAD

**Issue by abhishekmishragithub** [gdgchennai/devfest2022-web#12]

**Comment by abhishekmishragithub** [comment]
Looks like for the CFP form there is no embedding feature from sessionize.
 So just like the CFP URL: https://sessionize.com/devfest-chennai-2022
 
 cc: @StarkDroid

**Comment by StarkDroid** [comment]
> Looks like for the CFP form there is no embedding feature from sessionize. So just like the CFP URL: https://sessionize.com/devfest-chennai-2022
> 
> cc: @StarkDroid

So shall we just add a section and maybe add a button to redirect them to this page? 
If so, what should the section be called as?
