### ISSUE TITLE
Optimize images and implement lazy loading

### ISSUE THREAD

**Issue by moaqz** [gdgchennai/devfest2022-web#120]
Hello, I noticed the page could have a faster page load by optimizing the images. Here are the Lighthouse metrics:

![1](https://github.com/gdgchennai/devfest2022-web/assets/88462463/bece2914-40b8-4afc-afad-0d6fbc009dfa)
![2](https://github.com/gdgchennai/devfest2022-web/assets/88462463/739ca6f3-c7a3-498d-9ae3-0b318c35c3d6)

Here are the changes that can be made:

1. Optimize images
2. Use WebP format
3. Lazy load offscreen images
4. Set height and width for images

Can I work on these improvements?

**Comment by StarkDroid** [comment]
Happy to have contributions, go ahead!
