### ISSUE TITLE
Create sponsors section and add details

### ISSUE THREAD

**Issue by abhishekmishragithub** [gdgchennai/devfest2022-web#15]
Add a "Sponsor section" and inside that can we have lines something like this:
"Are you interested in supporting the event then drop an email to gdgchennaiteam[at]gmail[dot]com"?

**Comment by abhishekmishragithub** [comment]
@StarkDroid @Spikeysanju can we add a "Sponsor section" and inside that can we have lines something like this:
"Are you interested in supporting the event then drop an email to gdgchennaiteam[at]gmail[dot]com" ?

**Comment by abhishekmishragithub** [comment]
Adding - https://devfest.gdgjalandhar.com/ for reference.

cc: @StarkDroid @Spikeysanju @iamimmanuelraj

**Comment by StarkDroid** [comment]
We have the section, but like jalandhar did we could probably add buttons for
"Become a sponsor" with a google form and "sponsorship brochure"? 
@abhishekmishragithub
