### ISSUE TITLE
Ticket Showing halted post 11 am IST

### ISSUE THREAD

**Issue by Raghavi02bala** [gdgchennai/devfest2022-web#68]
The ticket was supposed to be open from 11 AM IST on 18-10-2022. But it's been 30 minutes and it's still in HALTED state.It would be better if you could update the website with tentative time.

**Comment by iamimmanuelraj** [comment]
Hi !

We are facing some issues and we will be back soon. Stay tuned

**Comment by navhits** [comment]
@Raghavi02bala the tickets will be live as soon we publish it on our social media channels (slack, twitter, instagram, linkedin)
