### ISSUE TITLE
Add YT live links as embedded previews or redirects

### ISSUE THREAD

**Issue by navhits** [gdgchennai/devfest2022-web#98]
Add YT live links.
Some YT channels might not have embed options enabled. In that case add a button alone on the home page. In the place of the two buttons in hero section. Replace them with these.

Day 1:
- Track 1 - https://www.youtube.com/watch?v=coFbkjbuMdA
- Track 2 - https://www.youtube.com/watch?v=B0SC-IzK0PQ

**Comment by navhits** [comment]
No live for Day 2

**Comment by StarkDroid** [comment]
Resolved
